Shopomo.Presentation.Admin/Controllers/LogAccessController.cs
using AutoMapper;
using Shopomo.Application.Interfaces;
using Shopomo.OTP.Domain.Entities;
using Shopomo.Presentation.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Shopomo.Presentation.Admin.Controllers
{
    [Authorize]
    public class LogAccessController : Controller
    {
        private readonly ILogAccessAppService _logAccessService;

        public LogAccessController(ILogAccessAppService logAccessService)
        {
            _logAccessService = logAccessService;
        }

        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> GetAll()
        {
            var logs = await _logAccessService.GetAllAsync();
            var logsViewModel = Mapper.Map<IEnumerable<LogAccess>, IEnumerable<LogAccessViewModel>>(logs);

            return Json(logsViewModel, JsonRequestBehavior.AllowGet);
        }
    }
}

Shopomo.Presentation.Admin/Controllers/UserController.cs
using AutoMapper;
using Shopomo.Application.Interfaces;
using Shopomo.OTP.Domain.Entities;
using Shopomo.Presentation.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Shopomo.Presentation.Admin.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserAppService _userService;

        public UserController(IUserAppService userService)
        {
            _userService = userService;
        }

        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(UserViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                var user = Mapper.Map<UserViewModel, User>(model);
                var userBd = await _userService.GetByEmailAsync(user.Email);
                if (userBd == null)
                {
                    var result = await _userService.AddAsync(user);

                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "Email já existe";
                    return View(model);
                }
                
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public async Task<ActionResult> GetAll()
        {
            var users = await _userService.GetAllAsync();
            var usersViewModel = Mapper.Map<IEnumerable<User>, IEnumerable<UserViewModel>>(users);

            return Json(usersViewModel, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int userId)
        {
            var user = await _userService.GetByIdAsync(userId);

            var result = await _userService.RemoveAsync(user);

            return result == 1 ? Json(true, JsonRequestBehavior.AllowGet) : Json(false, JsonRequestBehavior.AllowGet);

        }
    }
}

Shopomo.Presentation.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="app">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Shopomo Admin</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Shopomo Admin", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Users", "Index", "User")</li>
                    <li>@Html.ActionLink("Logs", "Index", "LogAccess")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Shopomo Admin</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angularjs")
    @Scripts.Render("~/bundles/toastr")
    @Scripts.Render("~/bundles/main")
    @RenderSection("scripts", required: false)
</body>
</html>